train_dir: "/home/baohoang235/WorkSpace/Infore/face-check-in/data/InfoRe"
test_dir: "data/test/"
model_dir: "trained/"
label_path: "/home/baohoang235/face-check-in/Bao/trained/1/labels.npy"
trained_model: "/home/baohoang235/face-check-in/Bao/trained/1/trained_knn_model.clf"
current_user_imgs_dir: 'data/train/'
database: '/home/baohoang235/face-check-in/database.db'
retrain_images_dir: '/home/baohoang235/face-check-in/retrain_images'
encoding_path: '/home/baohoang235/face-check-in/Bao/trained/1//encodings.npy'
save_dir: 'data/save_dir/'
font_path: 'font/architep.ttf'
thickness: 5
font_size: 60
n_neighbors: 20
face_thresh: 0.4
down_scale: 0.25
